version: '3.8'

services:
  app:
    build: .
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/assessment
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8888:8888"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: